### ISSUE TITLE
about Home UI

### ISSUE THREAD

**Issue by janakaedirisinghe** [gayanvoice/most-active-github-users-nodejs#32]
![image](https://user-images.githubusercontent.com/37530779/76348010-87b9cb80-632d-11ea-8dea-27633281e7d1.png)

Home page  not loading properly.

**Comment by gayanvoice** [comment]
Sorry, @janakaedirisinghe Last week I tried to update the UI and added some new feature called Stats http://www.githubstats.com/stats which actually generates page views of a particular repository. But due to lack of time, I had to push uncompleted and messy code. you can see it in server.js, it's actually a mess. Next few weeks, I will clean this up.
